"""add totp fields to users

Revision ID: 00f79c3e0a51
Revises: a7a416ed7176
Create Date: 2026-05-17 14:26:28.196546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f79c3e0a51'
down_revision = 'a7a416ed7176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('totp_backup_codes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_backup_codes')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
