"""add ticket_types table

Revision ID: 6e34a76e3995
Revises: 2023caa656f0
Create Date: 2026-05-13 21:14:05.859817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e34a76e3995'
down_revision = '2023caa656f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_total', sa.Integer(), nullable=False),
    sa.Column('seatable', sa.Boolean(), nullable=False),
    sa.Column('includes_lodging', sa.Boolean(), nullable=False),
    sa.Column('valid_days', sa.Text(), nullable=False),
    sa.Column('max_per_user', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_types')
    # ### end Alembic commands ###
