"""add game suggestions and votes

Revision ID: 9ab43e778a76
Revises: f4d8363eef8b
Create Date: 2026-05-15 12:19:21.688906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab43e778a76'
down_revision = 'f4d8363eef8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('suggested_by', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.Text(), nullable=False),
    sa.Column('bgg_id', sa.Integer(), nullable=True),
    sa.Column('steam_app_id', sa.Integer(), nullable=True),
    sa.Column('suggested_datetime', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['suggested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_suggestion_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['game_suggestions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suggestion_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_suggestion_votes')
    op.drop_table('game_suggestions')
    # ### end Alembic commands ###
