"""add game suggestion metadata fields

Revision ID: 9d135e9c593b
Revises: 2c142414df87
Create Date: 2026-05-16 12:06:28.165682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d135e9c593b'
down_revision = '2c142414df87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_image_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('game_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('game_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('game_min_players', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('game_max_players', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_suggestions', schema=None) as batch_op:
        batch_op.drop_column('game_max_players')
        batch_op.drop_column('game_min_players')
        batch_op.drop_column('game_year')
        batch_op.drop_column('game_description')
        batch_op.drop_column('game_image_url')

    # ### end Alembic commands ###
