"""add payment processor fields to registrations

Revision ID: a3a5041080ab
Revises: 2bbf3cf37d0e
Create Date: 2026-05-15 22:13:46.437117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a5041080ab'
down_revision = '2bbf3cf37d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_session_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('paypal_order_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payment_processor', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('payment_processor')
        batch_op.drop_column('paypal_order_id')
        batch_op.drop_column('stripe_session_id')

    # ### end Alembic commands ###
