"""Split user name into first_name, last_name, gamertag

Revision ID: b265c4afc066
Revises: 00f79c3e0a51
Create Date: 2026-06-10 19:43:03.080577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b265c4afc066'
down_revision = '00f79c3e0a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('last_name', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('gamertag', sa.Text(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=False, server_default=''))
        batch_op.drop_column('gamertag')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
